version: 2
jobs:
  build:
    docker:
      # Circle requires a lane
       - image: circleci/ruby
    working_directory: ~/cg-demos
    steps:
      - checkout
      - run:
          name: Setup CF CLI
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            cf api https://api.fr.cloud.gov  # alternately target your private Cloud Foundry deployment
            cf auth "$CF_USER" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"

  test:
    docker:
      # Circle requires a lane
       - image: circleci/ruby
    working_directory: ~/cg-demos
    steps:
      - run:
        name: Shell test
        command: ./test.sh live


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires: 
            - build

